# Generated by Django 4.1.1 on 2022-09-16 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='api',
            new_name='apis',
        ),
    ]
