# Generated by Django 4.1.1 on 2022-09-16 14:35

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_alter_apis_count_alter_apis_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='apis',
            managers=[
                ('search', django.db.models.manager.Manager()),
            ],
        ),
    ]
