# Generated by Django 4.1.1 on 2022-09-16 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_alter_apis_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='apis',
            managers=[
            ],
        ),
    ]
