# Generated by Django 4.1.1 on 2022-09-17 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_alter_apis_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apis',
            old_name='count',
            new_name='no',
        ),
    ]
