# Generated by Django 4.1.1 on 2022-09-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_rename_count_apis_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apis',
            name='no',
            field=models.IntegerField(blank=True),
        ),
    ]
