# Generated by Django 4.1.1 on 2022-09-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_alter_apis_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apis',
            name='username',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
