# Generated by Django 4.1.1 on 2022-09-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_alter_apis_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apis',
            name='no',
            field=models.PositiveSmallIntegerField(max_length=50),
        ),
    ]
