# Generated by Django 4.1.1 on 2022-09-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_alter_apis_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='apis',
            name='userid',
            field=models.CharField(default=96479162, max_length=122),
        ),
    ]
